# Generated by isa.py, do not edit.

OP_NOP   = 0   ; # 00
OP_OUT   = 3   ; # 03
OP_IN    = 5   ; # 05
OP_CALL  = 6   ; # 06
OP_CALLI = 7   ; # 07
OP_RET   = 8   ; # 08
OP_RETI  = 10  ; # 0A
OP_PUSH  = 12  ; # 0C
OP_POP   = 14  ; # 0E
OP_MUL   = 16  ; # 10
OP_MULI  = 17  ; # 11
OP_SMUL  = 18  ; # 12
OP_SMULI = 19  ; # 13
OP_J     = 96  ; # 60
OP_JI    = 97  ; # 61
OP_JEQ   = 98  ; # 62
OP_JEQI  = 99  ; # 63
OP_JCS   = 100 ; # 64
OP_JCSI  = 101 ; # 65
OP_JNEG  = 102 ; # 66
OP_JNEGI = 103 ; # 67
OP_JVS   = 104 ; # 68
OP_JVSI  = 105 ; # 69
OP_JHI   = 106 ; # 6A
OP_JHII  = 107 ; # 6B
OP_JGE   = 108 ; # 6C
OP_JGEI  = 109 ; # 6D
OP_JGT   = 110 ; # 6E
OP_JGTI  = 111 ; # 6F
OP_JNE   = 114 ; # 72
OP_JNEI  = 115 ; # 73
OP_JCC   = 116 ; # 74
OP_JCCI  = 117 ; # 75
OP_JPOS  = 118 ; # 76
OP_JPOSI = 119 ; # 77
OP_JVC   = 120 ; # 78
OP_JVCI  = 121 ; # 79
OP_JLS   = 122 ; # 7A
OP_JLSI  = 123 ; # 7B
OP_JLT   = 124 ; # 7C
OP_JLTI  = 125 ; # 7D
OP_JLE   = 126 ; # 7E
OP_JLEI  = 127 ; # 7F
OP_SUB   = 128 ; # 80
OP_SUBI  = 129 ; # 81
OP_SUBC  = 130 ; # 82
OP_SUBCI = 131 ; # 83
OP_ADD   = 132 ; # 84
OP_ADDI  = 133 ; # 85
OP_ADDC  = 134 ; # 86
OP_ADDCI = 135 ; # 87
OP_CMP   = 144 ; # 90
OP_CMPI  = 145 ; # 91
OP_SET   = 160 ; # A0
OP_CLR   = 162 ; # A2
OP_HLT   = 164 ; # A4
OP_INT   = 166 ; # A6
OP_TST   = 169 ; # A9
OP_MOV   = 170 ; # AA
OP_MOVI  = 171 ; # AB
OP_LDR   = 192 ; # C0
OP_LDRI  = 193 ; # C1
OP_STR   = 194 ; # C2
OP_STRI  = 195 ; # C3
OP_LDRB  = 196 ; # C4
OP_LDRBI = 197 ; # C5
OP_STRB  = 198 ; # C6
OP_STRBI = 199 ; # C7
OP_LDA   = 200 ; # C8
OP_STA   = 202 ; # CA
OP_LDAB  = 204 ; # CC
OP_STAB  = 206 ; # CE
OP_AND   = 224 ; # E0
OP_ANDI  = 225 ; # E1
OP_OR    = 226 ; # E2
OP_ORI   = 227 ; # E3
OP_XOR   = 228 ; # E4
OP_XORI  = 229 ; # E5
OP_LSL   = 230 ; # E6
OP_LSLI  = 231 ; # E7
OP_LSR   = 232 ; # E8
OP_LSRI  = 233 ; # E9
OP_ASL   = 234 ; # EA
OP_ASLI  = 235 ; # EB
OP_ASR   = 236 ; # EC
OP_ASRI  = 237 ; # ED
OP_NOT   = 238 ; # EE
OP_NOTI  = 239 ; # EF

predef_constants = {
	"Z_FLAG_BIT": 0,
	"C_FLAG_BIT": 2,
	"I_FLAG_BIT": 4,
	"V_FLAG_BIT": 1,
	"N_FLAG_BIT": 3,
	"Z_FLAG": 1,
	"C_FLAG": 4,
	"I_FLAG": 16,
	"V_FLAG": 2,
	"N_FLAG": 8,

	"IRQ_BUTTON2": 4,
	"IRQ_SD_CARD": 512,
	"IRQ_UART_RX": 128,
	"IRQ_BUTTON4": 16,
	"IRQ_KEYBOARD": 256,
	"IRQ_BUTTON0": 1,
	"IRQ_BUTTON5": 32,
	"IRQ_BUTTON1": 2,
	"IRQ_VBLANK": 64,
	"IRQ_BUTTON3": 8,
	"PORT_SD_ADDRESS" : 22,
	"PORT_PS2_TX_DATA" : 32,
	"PORT_SD_RX_DATA" : 23,
	"PORT_STATUS_REG" : 0,
	"PORT_PS2_RX_DATA" : 31,
	"PORT_BUTTONS" : 7,
	"PORT_IRQ_READY" : 3,
	"PORT_LED" : 5,
	"PORT_UART_FLAGS" : 10,
	"PORT_SD_FLAGS" : 20,
	"PORT_PS2_FLAGS" : 30,
	"PORT_UART_TX_DATA" : 11,
	"PORT_UART_RX_DATA" : 12,
	"PORT_SD_COMMAND" : 21,
	"PORT_SWITCHES" : 8,
	"PORT_IRQ_CLEAR" : 1,
	"PORT_IRQ_MASK" : 2,
	"PORT_SEVEN_SEG" : 6,
}