# Generated by isa.py, do not edit.

OP_NOP   = 0   ; # 00
OP_OUT   = 3   ; # 03
OP_IN    = 5   ; # 05
OP_CALL  = 6   ; # 06
OP_CALLI = 7   ; # 07
OP_RET   = 8   ; # 08
OP_RETI  = 10  ; # 0A
OP_PUSH  = 12  ; # 0C
OP_POP   = 14  ; # 0E
OP_MUL   = 16  ; # 10
OP_MULI  = 17  ; # 11
OP_SMUL  = 18  ; # 12
OP_SMULI = 19  ; # 13
OP_J     = 96  ; # 60
OP_JI    = 97  ; # 61
OP_JEQ   = 98  ; # 62
OP_JEQI  = 99  ; # 63
OP_JCS   = 100 ; # 64
OP_JCSI  = 101 ; # 65
OP_JNEG  = 102 ; # 66
OP_JNEGI = 103 ; # 67
OP_JVS   = 104 ; # 68
OP_JVSI  = 105 ; # 69
OP_JHI   = 106 ; # 6A
OP_JHII  = 107 ; # 6B
OP_JGE   = 108 ; # 6C
OP_JGEI  = 109 ; # 6D
OP_JGT   = 110 ; # 6E
OP_JGTI  = 111 ; # 6F
OP_JNE   = 114 ; # 72
OP_JNEI  = 115 ; # 73
OP_JCC   = 116 ; # 74
OP_JCCI  = 117 ; # 75
OP_JPOS  = 118 ; # 76
OP_JPOSI = 119 ; # 77
OP_JVC   = 120 ; # 78
OP_JVCI  = 121 ; # 79
OP_JLS   = 122 ; # 7A
OP_JLSI  = 123 ; # 7B
OP_JLT   = 124 ; # 7C
OP_JLTI  = 125 ; # 7D
OP_JLE   = 126 ; # 7E
OP_JLEI  = 127 ; # 7F
OP_SUB   = 128 ; # 80
OP_SUBI  = 129 ; # 81
OP_SUBC  = 130 ; # 82
OP_SUBCI = 131 ; # 83
OP_ADD   = 132 ; # 84
OP_ADDI  = 133 ; # 85
OP_ADDC  = 134 ; # 86
OP_ADDCI = 135 ; # 87
OP_CMP   = 144 ; # 90
OP_CMPI  = 145 ; # 91
OP_SET   = 160 ; # A0
OP_CLR   = 162 ; # A2
OP_HLT   = 164 ; # A4
OP_INT   = 167 ; # A7
OP_TST   = 169 ; # A9
OP_MOV   = 170 ; # AA
OP_MOVI  = 171 ; # AB
OP_LDR   = 192 ; # C0
OP_LDRI  = 193 ; # C1
OP_STR   = 194 ; # C2
OP_STRI  = 195 ; # C3
OP_LDRB  = 196 ; # C4
OP_LDRBI = 197 ; # C5
OP_STRB  = 198 ; # C6
OP_STRBI = 199 ; # C7
OP_LDA   = 200 ; # C8
OP_STA   = 202 ; # CA
OP_LDAB  = 204 ; # CC
OP_STAB  = 206 ; # CE
OP_AND   = 224 ; # E0
OP_ANDI  = 225 ; # E1
OP_OR    = 226 ; # E2
OP_ORI   = 227 ; # E3
OP_XOR   = 228 ; # E4
OP_XORI  = 229 ; # E5
OP_LSL   = 230 ; # E6
OP_LSLI  = 231 ; # E7
OP_LSR   = 232 ; # E8
OP_LSRI  = 233 ; # E9
OP_ASL   = 234 ; # EA
OP_ASLI  = 235 ; # EB
OP_ASR   = 236 ; # EC
OP_ASRI  = 237 ; # ED
OP_NOT   = 238 ; # EE
OP_NOTI  = 239 ; # EF

predef_constants = {
	"N_FLAG": 3,
	"V_FLAG": 1,
	"I_FLAG": 4,
	"C_FLAG": 2,
	"Z_FLAG": 0,

	"IRQ_INT6": 64,
	"IRQ_BUTTON4": 16,
	"IRQ_TIMER1": 1024,
	"IRQ_KEYBOARD": 256,
	"IRQ_BUTTON5": 32,
	"IRQ_BUTTON0": 1,
	"IRQ_UART_RX": 128,
	"IRQ_BUTTON2": 4,
	"IRQ_SD_CARD": 512,
	"IRQ_BUTTON1": 2,
	"IRQ_TIMER2": 2048,
	"IRQ_BUTTON3": 8,
	"PORT_SWITCHES" : 8,
	"PORT_PS2_FLAGS" : 30,
	"PORT_TIMER1_TOP" : 40,
	"PORT_PS2_TX_DATA" : 32,
	"PORT_TIMER2_ENABLED" : 53,
	"PORT_TIMER2_VALUE" : 51,
	"PORT_UART_RX_DATA" : 12,
	"PORT_UART_FLAGS" : 10,
	"PORT_UART_TX_DATA" : 11,
	"PORT_SD_RX_DATA" : 23,
	"PORT_TIMER1_RESTART" : 42,
	"PORT_TIMER1_ENABLED" : 43,
	"PORT_LED" : 5,
	"PORT_SD_ADDRESS" : 22,
	"PORT_BUTTONS" : 7,
	"PORT_SD_COMMAND" : 21,
	"PORT_PS2_RX_DATA" : 31,
	"PORT_SEVEN_SEG" : 6,
	"PORT_TIMER1_VALUE" : 41,
	"PORT_STATUS_REG" : 0,
	"PORT_TIMER2_RESTART" : 52,
	"PORT_IRQ_CLEAR" : 1,
	"PORT_TIMER2_TOP" : 50,
	"PORT_IRQ_MASK" : 2,
	"PORT_IRQ_READY" : 3,
	"PORT_SD_FLAGS" : 20,
}

op_table={
	"NOP": 0,
	"OUT": 3,
	"IN": 5,
	"CALL": 6,
	"CALLI": 7,
	"RET": 8,
	"RETI": 10,
	"PUSH": 12,
	"POP": 14,
	"MUL": 16,
	"MULI": 17,
	"SMUL": 18,
	"SMULI": 19,
	"J": 96,
	"JI": 97,
	"JEQ": 98,
	"JEQI": 99,
	"JCS": 100,
	"JCSI": 101,
	"JNEG": 102,
	"JNEGI": 103,
	"JVS": 104,
	"JVSI": 105,
	"JHI": 106,
	"JHII": 107,
	"JGE": 108,
	"JGEI": 109,
	"JGT": 110,
	"JGTI": 111,
	"JNE": 114,
	"JNEI": 115,
	"JCC": 116,
	"JCCI": 117,
	"JPOS": 118,
	"JPOSI": 119,
	"JVC": 120,
	"JVCI": 121,
	"JLS": 122,
	"JLSI": 123,
	"JLT": 124,
	"JLTI": 125,
	"JLE": 126,
	"JLEI": 127,
	"SUB": 128,
	"SUBI": 129,
	"SUBC": 130,
	"SUBCI": 131,
	"ADD": 132,
	"ADDI": 133,
	"ADDC": 134,
	"ADDCI": 135,
	"CMP": 144,
	"CMPI": 145,
	"SET": 160,
	"CLR": 162,
	"HLT": 164,
	"INT": 167,
	"TST": 169,
	"MOV": 170,
	"MOVI": 171,
	"LDR": 192,
	"LDRI": 193,
	"STR": 194,
	"STRI": 195,
	"LDRB": 196,
	"LDRBI": 197,
	"STRB": 198,
	"STRBI": 199,
	"LDA": 200,
	"STA": 202,
	"LDAB": 204,
	"STAB": 206,
	"AND": 224,
	"ANDI": 225,
	"OR": 226,
	"ORI": 227,
	"XOR": 228,
	"XORI": 229,
	"LSL": 230,
	"LSLI": 231,
	"LSR": 232,
	"LSRI": 233,
	"ASL": 234,
	"ASLI": 235,
	"ASR": 236,
	"ASRI": 237,
	"NOT": 238,
	"NOTI": 239,
}
